### ISSUE TITLE
Return object back to original UI location on non-match or no comparison made

### ISSUE THREAD

**Issue by burrage** [curiouslearning/workshops_find_two_match_2#29]
**User Story:**
As a child,
I want an object to return to its original place in the UI if it doesn’t correctly match another object or if a comparison between two objects was not made,
So that I can try to drag the object near another object again.

**Acceptance Criteria:**
Given that I have dragged an object from one side of the screen near another object on the other side of the screen,
When I have heard and seen the negative feedback,
Then I want the object to return to the original place in the UI before I began dragging it.

Given that I have dragged an object and haven’t placed it near another object on the other side of the screen to elicit a comparison,
When I release my finger from dragging the object,
Then I want the object to return to the original place in the UI before I began dragging it.

**Comment by deannah** [comment]
This ﻿partially disagrees with the s﻿pec. It agrees that if an incorrect match was made, the dragged object should return to where it had been, but it also says "A child can drag around an object and leave it anywhere". I'd be fine with ﻿implementing either, I just wanna know which is right.

**Comment by burrage** [comment]
@deannah Good catch! This might be something worthwhile for user testing but when you get to this point, my rule of thumb is always go the simpler route first.

Let's nix the "leave it anywhere"-- there are possibilities that allowing that freedom will only muddle the guidance of what we really want them to do.
