### ISSUE TITLE
Highlight word and play audio of the word on touch

### ISSUE THREAD

**Issue by burrage** [curiouslearning/workshops_find_two_match_2#49]
**User Story:**
As a child,
I want to hear the spoken audio of a word play when I touch a word and for the word to be highlighted in the UI throughout the duration of the spoken audio before returning to its normal state,
So that I can make a visual and auditory connection between a word on the screen and what it sounds like.

**Acceptance Criteria:**
Given that I am viewing either the "You win!" or "Let's play!" screen (or any subsequent screen that has words),
When I tap a word,
Then audio of the word being spoken is played and the word is highlighted in the UI until the audio finishes playing.

**Comment by deannah** [comment]
I finished this based on what I remembered of our discussion of it, so now when 'tú ganas' a﻿p﻿pears on screen its audio is ﻿played.

**Comment by burrage** [comment]
@deannah That's great!
